export const GET_CHARACTERS_REQUEST = "GET_CHARACTERS_REQUEST";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_FAIL = "GET_CHARACTERS_FAIL";
export const GET_CHARACTERS_RESET = "GET_CHARACTERS_RESET";

export const CREATE_CHARACTER_REQUEST = "CREATE_CHARACTER_REQUEST";
export const CREATE_CHARACTER_SUCCESS = "CREATE_CHARACTER_SUCCESS";
export const CREATE_CHARACTER_FAIL = "CREATE_CHARACTER_FAIL";
export const CREATE_CHARACTER_RESET = "CREATE_CHARACTER_RESET";

export const UPDATE_CHARACTER_REQUEST = "UPDATE_CHARACTER_REQUEST";
export const UPDATE_CHARACTER_SUCCESS = "UPDATE_CHARACTER_SUCCESS";
export const UPDATE_CHARACTER_FAIL = "UPDATE_CHARACTER_FAIL";
export const UPDATE_CHARACTER_RESET = "UPDATE_CHARACTER_RESET";

export const DELETE_CHARACTER_REQUEST = "DELETE_CHARACTER_REQUEST";
export const DELETE_CHARACTER_SUCCESS = "DELETE_CHARACTER_SUCCESS";
export const DELETE_CHARACTER_FAIL = "DELETE_CHARACTER_FAIL";
export const DELETE_CHARACTER_RESET = "DELETE_CHARACTER_RESET";
