export const USER_GET_FAVORITE_MOVIES_REQUEST =
  "USER_GET_FAVORITE_MOVIES_REQUEST";
export const USER_GET_FAVORITE_MOVIES_SUCCESS =
  "USER_GET_FAVORITE_MOVIES_SUCCESS";
export const USER_GET_FAVORITE_MOVIES_UPDATED =
  "USER_GET_FAVORITE_MOVIES_UPDATED";
export const USER_GET_FAVORITE_MOVIES_FAIL = "USER_GET_FAVORITE_MOVIES_FAIL";
export const USER_GET_FAVORITE_MOVIES_RESET = "USER_GET_FAVORITE_MOVIES_RESET";

export const USER_ADD_FAVORITE_MOVIE_REQUEST =
  "USER_ADD_FAVORITE_MOVIE_REQUEST";
export const USER_ADD_FAVORITE_MOVIE_SUCCESS =
  "USER_ADD_FAVORITE_MOVIE_SUCCESS";
export const USER_ADD_FAVORITE_MOVIE_FAIL = "USER_ADD_FAVORITE_MOVIE_FAIL";
export const USER_ADD_FAVORITE_MOVIE_RESET = "USER_ADD_FAVORITE_MOVIE_RESET";

export const USER_DELETE_FAVORITE_MOVIE_REQUEST =
  "USER_DELETE_FAVORITE_MOVIE_REQUEST";
export const USER_DELETE_FAVORITE_MOVIE_SUCCESS =
  "USER_DELETE_FAVORITE_MOVIE_SUCCESS";
export const USER_DELETE_FAVORITE_MOVIE_FAIL =
  "USER_DELETE_FAVORITE_MOVIE_FAIL";
export const USER_DELETE_FAVORITE_MOVIE_RESET =
  "USER_DELETE_FAVORITE_MOVIE_RESET";

export const USER_DELETE_ALL_FAVORITE_MOVIES_REQUEST =
  "USER_DELETE_ALL_FAVORITE_MOVIES_REQUEST";
export const USER_DELETE_ALL_FAVORITE_MOVIES_SUCCESS =
  "USER_DELETE_ALL_FAVORITE_MOVIES_SUCCESS";
export const USER_DELETE_ALL_FAVORITE_MOVIES_FAIL =
  "USER_DELETE_ALL_FAVORITE_MOVIES_FAIL";
export const USER_DELETE_ALL_FAVORITE_MOVIES_RESET =
  "USER_DELETE_ALL_FAVORITE_MOVIES_RESET";
