export const GET_ALL_MOVIES_REQUEST = "GET_ALL_MOVIES_REQUEST";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAIL = "GET_ALL_MOVIES_FAIL";
export const GET_ALL_MOVIES_RESET = "GET_ALL_MOVIES_RESET";
export const GET_ALL_MOVIES_AFTER_DELETE = "GET_ALL_MOVIES_AFTER_DELETE";
// export const GET_ALL_MOVIES_AFTER_CREATE = "GET_ALL_MOVIES_AFTER_CREATE";
// export const GET_ALL_MOVIES_AFTER_UPDATE = "GET_ALL_MOVIES_AFTER_UPDATE";

export const GET_RANDOM_MOVIES_REQUEST = "GET_RANDOM_MOVIES_REQUEST";
export const GET_RANDOM_MOVIES_SUCCESS = "GET_RANDOM_MOVIES_SUCCESS";
export const GET_RANDOM_MOVIES_FAIL = "GET_RANDOM_MOVIES_FAIL";
export const GET_RANDOM_MOVIES_RESET = "GET_RANDOM_MOVIES_RESET";

export const GET_TOP_RATED_MOVIES_REQUEST = "GET_TOP_RATED_MOVIES_REQUEST";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";
export const GET_TOP_RATED_MOVIES_FAIL = "GET_TOP_RATED_MOVIES_FAIL";
export const GET_TOP_RATED_MOVIES_RESET = "GET_TOP_RATED_MOVIES_RESET";

export const GET_MOVIE_BY_ID_REQUEST = "GET_MOVIE_BY_ID_REQUEST";
export const GET_MOVIE_BY_ID_SUCCESS = "GET_MOVIE_BY_ID_SUCCESS";
export const GET_MOVIE_BY_ID_FAIL = "GET_MOVIE_BY_ID_FAIL";
export const GET_MOVIE_BY_ID_RESET = "GET_MOVIE_BY_ID_RESET";

export const GET_MOVIE_URL_BY_ID_REQUEST = "GET_MOVIE_URL_BY_ID_REQUEST";
export const GET_MOVIE_URL_BY_ID_SUCCESS = "GET_MOVIE_URL_BY_ID_SUCCESS";
export const GET_MOVIE_URL_BY_ID_FAIL = "GET_MOVIE_URL_BY_ID_FAIL";
export const GET_MOVIE_URL_BY_ID_RESET = "GET_MOVIE_URL_BY_ID_RESET";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";
export const DELETE_MOVIE_RESET = "DELETE_MOVIE_RESET";

export const UPLOAD_MOVIE_REQUEST = "UPLOAD_MOVIE_REQUEST";
export const UPLOAD_MOVIE_SUCCESS = "UPLOAD_MOVIE_SUCCESS";
export const UPLOAD_MOVIE_FAIL = "UPLOAD_MOVIE_FAIL";
export const UPLOAD_MOVIE_RESET = "UPLOAD_MOVIE_RESET";
