#spring.application.name=movie-website
server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: ${DBMS_URL:jdbc:mysql://localhost:3306/movie-website}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:dong_nv}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "YFk388TsWvGVx7Cw7yRdkJgrW57GDsA3StLwX/VcWScQpUQv5alGL7BxqzRVbHbb"
  accessTokenExpiration: 100 # in mintues
  refreshTokenExpiration: 1440 # in minutes
  issuer: "movie_website"