#spring.application.name=movie-website
server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: ${DBMS_URL:jdbc:mysql://localhost:3306/movie-website}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:dong_nv}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "dongnv4724@gmail.com"
    password: "sced efri gxhe zolz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "smtp.gmail.com"
  redis:
    host: "localhost"
    port: 6379


jwt:
  signerKey: "YFk388TsWvGVx7Cw7yRdkJgrW57GDsA3StLwX/VcWScQpUQv5alGL7BxqzRVbHbb"
  accessTokenExpiration: 6000 # in mintues
  refreshTokenExpiration: 1440 # in minutes
  issuer: "movie_website"

aws:
  access: "AKIA257JESJHPOIJAYNU"
  secret: "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"
  s3:
    bucketName: "movie-website-stograge"
    region: "ap-southeast-2"
    folderName: "movie"
    publicFolder: "public"
    cdnName: "https://movie-website-stograge.s3.ap-southeast-2.amazonaws.com/"

#springdoc:
#  api-docs:
#    path: /api-docs #default is /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui-custom.html  # default is: /swagger-ui.html
##    operationSorter: "method"  # Sort by http method