#spring.application.name=movie-website
server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: ${DBMS_URL:jdbc:mysql://localhost:3306/movie-website}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:dong_nv}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "dongnv4724@gmail.com"
    password: "sced efri gxhe zolz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "smtp.gmail.com"
  redis:
    host: "localhost"
    port: 6379


jwt:
  signerKey: "YFk388TsWvGVx7Cw7yRdkJgrW57GDsA3StLwX/VcWScQpUQv5alGL7BxqzRVbHbb"
  accessTokenExpiration: 100 # in mintues
  refreshTokenExpiration: 1440 # in minutes
  issuer: "movie_website"

#springdoc:
#  api-docs:
#    path: /api-docs #default is /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui-custom.html  # default is: /swagger-ui.html
##    operationSorter: "method"  # Sort by http method